name: Return HTTP Response
on:
  repository_dispatch:
    types: [trigger-http-hook]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Response
        uses: teknofire/gh-action-http-response@v1
        with:
          status: '200'
          body: '{"message": "Action triggered successfully!"}'
